type Word = {
  display: string;
  kana: string;
  url: string;
  book: {
    name: string;
    author: string;
  };
};

const words: Word[] = [
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "芥川龍之介", name: "鼻" },
  },
  {
    display: "一人の下人が、羅生門の下で雨やみを待っていた。",
    kana: "ひとりのげにんが、らしょうもんのしたであめやみをまっていた。",
    url: "https://www.aozora.gr.jp/cards/000879/files/127_15260.html",
    book: {
      name: "羅生門",
      author: "芥川龍之介",
    },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "芥川龍之介", name: "地獄変" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "芥川龍之介", name: "藪の中" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "有島武郎", name: "カインの末裔" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "有島武郎", name: "或る女" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "泉鏡花", name: "高野聖" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "泉鏡花", name: "婦系図" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "伊藤左千夫", name: "野菊の墓" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "井伏鱒二", name: "山椒魚" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "上田秋成", name: "雨月物語" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "内田百閒", name: "冥途" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "内田百閒", name: "山高帽子" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "江戸川乱歩", name: "人間椅子" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "江戸川乱歩", name: "二銭銅貨" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "江戸川乱歩", name: "屋根裏の散歩者" },
  },
  {
    display: "私は、その男の写真を三葉、見たことがある。",
    kana: "わたしは、そのおとこのしゃしんをさんば、みたことがある。",
    url: "https://www.aozora.gr.jp/cards/000035/files/301_14912.html",
    book: {
      name: "人間失格",
      author: "太宰治",
    },
  },
  {
    display: "メロスは激怒した。",
    kana: "めろすはげきどした。",
    url: "https://www.aozora.gr.jp/cards/000035/files/1567_14913.html",
    book: {
      name: "走れメロス",
      author: "太宰治",
    },
  },
  { display: "", kana: "", url: "", book: { author: "太宰治", name: "斜陽" } },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "太宰治", name: "ヴィヨンの妻" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "岡本綺堂", name: "半七捕物帳" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "小川未明", name: "赤い蝋燭と人魚" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "小川未明", name: "野ばら" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "小栗虫太郎", name: "黒死館殺人事件" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "梶井基次郎", name: "檸檬" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "梶井基次郎", name: "桜の樹の下には" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "菊池寛", name: "恩讐の彼方に" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "菊池寛", name: "藤十郎の恋" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "国木田独歩", name: "武蔵野" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "国木田独歩", name: "牛肉と馬鈴薯" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "久生十蘭", name: "顎十郎捕物帳" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "坂口安吾", name: "白痴" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "坂口安吾", name: "桜の森の満開の下" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "佐々木味津三", name: "右門捕物帖" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "佐藤春夫", name: "田園の憂鬱" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "佐藤紅緑", name: "あゝ玉杯に花うけて" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "志賀直哉", name: "城の崎にて" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "志賀直哉", name: "小僧の神様" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "島崎藤村", name: "破戒" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "島崎藤村", name: "夜明け前" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "鈴木三重吉", name: "デイモンとピシアス" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "谷崎潤一郎", name: "痴人の愛" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "谷崎潤一郎", name: "刺青" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "田中貢太郎", name: "日本怪談全集" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "田山花袋", name: "蒲団" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "坪内逍遥", name: "当世書生気質" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "徳田秋声", name: "新世帯" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "中勘助", name: "銀の匙" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "中島敦", name: "山月記" },
  },
  { display: "", kana: "", url: "", book: { author: "中島敦", name: "李陵" } },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "直木三十五", name: "南国太平記" },
  },
  {
    display: "吾輩は猫である。名前はまだ無い。",
    kana: "わがはいはねこである。なまえはまだない。",
    url: "https://www.aozora.gr.jp/cards/000148/files/789_14547.html",
    book: {
      name: "吾輩は猫である",
      author: "夏目漱石",
    },
  },
  {
    display: "親譲りの無鉄砲で小供の時から損ばかりしている。",
    kana: "おやゆずりのむてっぽうでこどものときからそんばかりしている",
    url: "https://www.aozora.gr.jp/cards/000148/files/752_14964.html",
    book: {
      name: "坊っちゃん",
      author: "夏目漱石",
    },
  },
  {
    display: "山路を登りながら、こう考えた。",
    kana: "やまみちをのぼりながら、こうかんがえた。",
    url: "https://www.aozora.gr.jp/cards/000148/files/776_14941.html",
    book: {
      name: "草枕",
      author: "夏目漱石",
    },
  },
  {
    display: "私はその人を常に先生と呼んでいた。",
    kana: "わたしはそのひとをつねにせんせいとよんでいた。",
    url: "https://www.aozora.gr.jp/cards/000148/files/772_14947.html",
    book: {
      name: "こころ",
      author: "夏目漱石",
    },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "夏目漱石", name: "三四郎" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "野村胡堂", name: "銭形平次捕物控" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "長谷川伸", name: "瞼の母" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "樋口一葉", name: "たけくらべ" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "樋口一葉", name: "にごりえ" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "広津和郎", name: "神経病時代" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "林芙美子", name: "放浪記" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "平林初之輔", name: "探偵小説論" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "牧野信一", name: "地獄の門" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "宮沢賢治", name: "銀河鉄道の夜" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "宮沢賢治", name: "注文の多い料理店" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "宮沢賢治", name: "風の又三郎" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "水谷準", name: "心理試験" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "村山槐多", name: "悪魔の舌" },
  },
  { display: "", kana: "", url: "", book: { author: "森鴎外", name: "舞姫" } },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "森鴎外", name: "高瀬舟" },
  },
  { display: "", kana: "", url: "", book: { author: "森鴎外", name: "雁" } },
  { display: "", kana: "", url: "", book: { author: "柳川春葉", name: "誓" } },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "山田美妙", name: "武蔵野" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "山本周五郎", name: "樅ノ木は残った" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "山本周五郎", name: "日本婦道記" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "夢野久作", name: "ドグラ・マグラ" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "夢野久作", name: "瓶詰地獄" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "ラフカディオ・ハーン", name: "怪談" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "小泉八雲", name: "耳無芳一の話" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "若山牧水", name: "黒松" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "和辻哲郎", name: "或る思想家の手記" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "海野十三", name: "電気風呂の怪死事件" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "黒岩涙香", name: "無惨" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "岡本かの子", name: "老妓抄" },
  },
  { display: "", kana: "", url: "", book: { author: "横光利一", name: "蝿" } },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "横光利一", name: "機械" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "吉川英治", name: "宮本武蔵" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "吉川英治", name: "三国志" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "直木三十五", name: "大阪を歩く" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "泉鏡花", name: "照葉狂言" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "菊池寛", name: "真珠夫人" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "国枝史郎", name: "神州纐纈城" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "佐藤垢石", name: "川中島合戦" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "田中啓文", name: "怪談集 （短編小説枠" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "中里介山", name: "大菩薩峠" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "野上弥生子", name: "迷路" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "服部之総", name: "赤道を越えて" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "水上瀧太郎", name: "貝殻追放" },
  },
  {
    display: "",
    kana: "",
    url: "",
    book: { author: "山川方夫", name: "箱の中のあなた" },
  },
];
