// 各配列の配列図を定義する
import type { KeyCode, LayoutId } from "@japanese-layout-analyzer/core";

type Character = string;

export type LayoutDiagram = Partial<Record<KeyCode, Character>>;

export type LayoutDiagramEntry = {
  name: string;
  diagram: LayoutDiagram;
};

export type LayoutDiagrams = LayoutDiagramEntry[];

const qwerty: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "Q",
      w: "W",
      e: "E",
      r: "R",
      t: "T",
      y: "Y",
      u: "U",
      i: "I",
      o: "O",
      p: "P",
      a: "A",
      s: "S",
      d: "D",
      f: "F",
      g: "G",
      h: "H",
      j: "J",
      k: "K",
      l: "L",
      Semicolon: ";",
      z: "Z",
      x: "X",
      c: "C",
      v: "V",
      b: "B",
      n: "N",
      m: "M",
      Comma: ",",
      Period: ".",
      Slash: "/",
    },
  },
];

const oonisi: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "Q",
      w: "L",
      e: "U",
      r: ",",
      t: ".",
      y: "F",
      u: "W",
      i: "R",
      o: "Y",
      p: "P",
      a: "E",
      s: "I",
      d: "A",
      f: "O",
      g: "-",
      h: "K",
      j: "T",
      k: "N",
      l: "S",
      Semicolon: "H",
      z: "Z",
      x: "X",
      c: "C",
      v: "V",
      b: ";",
      n: "G",
      m: "D",
      Comma: "M",
      Period: "J",
      Slash: "B",
      Minus: "/",
    },
  },
];

const hana: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "ょ",
      w: "て",
      e: "と",
      r: "こ",
      t: "は",
      y: "っ",
      u: "く",
      i: "う",
      o: "る",
      p: "ら",
      BracketLeft: "ー",
      a: "す",
      s: "か",
      d: "☆",
      f: "き",
      g: "た",
      h: "ん",
      j: "れ",
      k: "☆",
      l: "゛",
      Semicolon: "ろ",
      Quote: "り",
      z: "さ",
      x: "し",
      c: "な",
      v: "の",
      b: "に",
      n: "し",
      m: "つ",
      Comma: "。",
      Period: "、",
      Slash: "め",
      IntlRo: "え",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "ひ",
      w: "け",
      e: "ぇ",
      r: "ほ",
      t: "へ",
      y: "ゃ",
      u: "ま",
      i: "そ",
      o: "も",
      p: "ぃ",
      BracketLeft: "「",
      a: "ぁ",
      s: "よ",
      d: "ゅ",
      f: "や",
      g: "゜",
      h: "よ",
      j: "ふ",
      k: "ち",
      l: "む",
      Semicolon: "ぉ",
      Quote: "」",
      z: "ぅ",
      x: "せ",
      c: "あ",
      v: "わ",
      b: "ゆ",
      n: "ね",
      m: "み",
      Comma: "を",
      Period: "お",
      Slash: "ぬ",
      IntlRo: "　",
    },
  },
];

const tsuki2263: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "そ",
      w: "こ",
      e: "し",
      r: "て",
      t: "ょ",
      y: "つ",
      u: "ん",
      i: "い",
      o: "の",
      p: "り",
      BracketLeft: "ち",
      a: "は",
      s: "か",
      d: "☆",
      f: "と",
      g: "た",
      h: "く",
      j: "う",
      k: "★",
      l: "゛",
      Semicolon: "き",
      Quote: "れ",
      z: "す",
      x: "け",
      c: "に",
      v: "な",
      b: "さ",
      n: "っ",
      m: "る",
      Comma: "、",
      Period: "。",
      Slash: "゜",
      IntlRo: "・",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "ぁ",
      w: "ひ",
      e: "ほ",
      r: "ふ",
      t: "め",
      y: "ぬ",
      u: "え",
      i: "み",
      o: "や",
      p: "ぇ",
      BracketLeft: "「",
      a: "ぃ",
      s: "を",
      d: "ら",
      f: "あ",
      g: "よ",
      h: "ま",
      j: "お",
      k: "も",
      l: "わ",
      Semicolon: "ゆ",
      Quote: "」",
      z: "ぅ",
      x: "へ",
      c: "せ",
      v: "ゅ",
      b: "ゃ",
      n: "む",
      m: "ろ",
      Comma: "ね",
      Period: "ー",
      Slash: "ぉ",
      IntlRo: "　",
    },
  },
];

const tukiringo: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "せ",
      w: "こ",
      e: "ょ",
      r: "ら",
      t: "さ",
      y: "や",
      u: "す",
      i: "゛",
      o: "ん",
      p: "ゃ",
      BracketLeft: "ー",
      ControlLeft: "き",
      a: "れ",
      s: "し",
      d: "て",
      f: "と",
      g: "く",
      h: "は",
      j: "か",
      k: "い",
      l: "う",
      Semicolon: "る",
      Quote: "っ",
      z: "ち",
      x: "よ",
      c: "に",
      v: "の",
      b: "ゅ",
      n: "な",
      m: "た",
      Comma: "お",
      Period: "め",
      Slash: "つ",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "ぁ",
      w: "ぃ",
      e: "ょ",
      r: "け",
      t: "ろ",
      y: "ほ",
      u: "ね",
      i: "",
      o: "み",
      p: "ぉ",
      BracketLeft: "ぅ",
      ControlLeft: "",
      a: "ふ",
      s: "",
      d: "ぬ",
      f: "り",
      g: "。",
      h: "、",
      j: "あ",
      k: "ま",
      l: "え",
      Semicolon: "へ",
      Quote: "む",
      z: "",
      x: "ゎ",
      c: "",
      v: "も",
      b: "ひ",
      n: "そ",
      m: "を",
      Comma: "わ",
      Period: "ゆ",
      Slash: "ぇ",
    },
  },
];

const hybridTsuki: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "ま",
      w: "て",
      e: "た",
      r: "っ",
      t: "を",
      y: "ぇ",
      u: "に",
      i: "な",
      o: "の",
      p: "ゅ",
      BracketLeft: "ぱ",
      a: "？",
      s: "う",
      d: "、",
      f: "し",
      g: "が",
      h: "お",
      j: "い",
      k: "。",
      l: "と",
      Semicolon: "か",
      Quote: "ょ",
      z: "は",
      x: "も",
      c: "る",
      v: "こ",
      b: "ら",
      n: "く",
      m: "ん",
      Comma: "す",
      Period: "で",
      Slash: "ゃ",
    },
  },
  {
    name: "。シフト",
    diagram: {
      q: "ぎ",
      w: "ぐ",
      e: "ふ",
      r: "ゔ",
      t: "",
      y: "",
      u: "",
      i: "",
      o: "",
      p: "びゅ",
      BracketLeft: "",
      a: "ば",
      s: "ぶ",
      d: "べ",
      f: "せ",
      g: "む",
      h: "ぼ",
      j: "び",
      k: "や",
      l: "つ",
      Semicolon: "れ",
      Quote: "びょ",
      z: "",
      x: "",
      c: "",
      v: "き",
      b: "",
      n: "",
      m: "ほ",
      Comma: "",
      Period: "",
      Slash: "びゃ",
      IntlRo: "",
    },
  },
  {
    name: "、シフト",
    diagram: {
      q: "",
      w: "",
      e: "",
      r: "",
      t: "",
      y: "",
      u: "",
      i: "ひ",
      o: "み",
      p: "ご",
      BracketLeft: "",
      a: "あ",
      s: "ち",
      d: "え",
      f: "だ",
      g: "げ",
      h: "",
      j: "り",
      k: "よ",
      l: "そ",
      Semicolon: "け",
      Quote: "",
      z: "",
      x: "",
      c: "",
      v: "め",
      b: "",
      n: "",
      m: "ぬ",
      Comma: "ね",
      Period: "",
      Slash: "",
      IntlRo: "",
    },
  },
  {
    name: "？シフト",
    diagram: {
      q: "",
      w: "",
      e: "",
      r: "",
      t: "",
      y: "",
      u: "",
      i: "へ",
      o: "ゆ",
      p: "じゅ",
      BracketLeft: "",
      a: "ざ",
      s: "ず",
      d: "ぜ",
      f: "さ",
      g: "",
      h: "ぞ",
      j: "じ",
      k: "ど",
      l: "わ",
      Semicolon: "ろ",
      Quote: "じょ",
      z: "",
      x: "",
      c: "",
      v: "",
      b: "",
      n: "",
      m: "",
      Comma: "",
      Period: "",
      Slash: "じゃ",
      IntlRo: "",
    },
  },
];

const yukika: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "こ",
      w: "な",
      e: "と",
      r: "け",
      t: "ろ",
      y: "む",
      u: "る",
      i: "い",
      o: "の",
      p: "れ",
      BracketLeft: "め",
      a: "た",
      s: "て",
      d: "☆",
      f: "か",
      g: "は",
      h: "っ",
      j: "ん",
      k: "☆",
      l: "゛",
      Semicolon: "し",
      Quote: "ー",
      z: "す",
      x: "ょ",
      c: "せ",
      v: "き",
      b: "さ",
      n: "く",
      m: "う",
      Comma: "、",
      Period: "。",
      Slash: "゜",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "ぁ",
      w: "ね",
      e: "や",
      r: "ほ",
      t: "ゆ",
      y: "ぬ",
      u: "わ",
      i: "あ",
      o: "に",
      p: "ぇ",
      BracketLeft: "「",
      a: "ぃ",
      s: "お",
      d: "ら",
      f: "も",
      g: "ふ",
      h: "ゃ",
      j: "つ",
      k: "ま",
      l: "ち",
      Semicolon: "え",
      Quote: "」",
      z: "ぅ",
      x: "ゅ",
      c: "そ",
      v: "よ",
      b: "へ",
      n: "み",
      m: "り",
      Comma: "ひ",
      Period: "を",
      Slash: "ぉ",
      IntlRo: "",
    },
  },
];

const mizunara: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "も",
      w: "に",
      e: "は",
      r: "て",
      t: "で",
      y: "れ",
      u: "っ",
      i: "し",
      o: "と",
      p: "の",
      a: "か",
      s: "★",
      d: "☆",
      f: "な",
      g: "る",
      h: "き",
      j: "ん",
      k: "☆",
      l: "★",
      Semicolon: "い",
      z: "こ",
      x: "が",
      c: "だ",
      v: "た",
      b: "ょ",
      n: "く",
      m: "う",
      Comma: "、",
      Period: "。",
    },
  },
  {
    name: "☆シフト",
    diagram: {
      q: "ご",
      w: "づ",
      e: "ぼ",
      r: "ほ",
      t: "へ",
      y: "ぉ",
      u: "ぷ",
      i: "ぶ",
      o: "え",
      p: "ゃ",
      a: "あ",
      s: "け",
      d: "す",
      f: "お",
      g: "さ",
      h: "ひ",
      j: "つ",
      k: "ち",
      l: "じ",
      Semicolon: "ま",
      z: "や",
      x: "ゆ",
      c: "ぜ",
      v: "ね",
      b: "よ",
      n: "ぬ",
      m: "み",
      Comma: "ぺ",
      Period: "ゅ",
      Slash: "ぴ",
    },
  },
  {
    name: "★シフト",
    diagram: {
      q: "べ",
      w: "ぃ",
      e: "ぁ",
      r: "ど",
      t: "ぞ",
      y: "　",
      u: "ぱ",
      i: "ぽ",
      o: "ば",
      p: "ず",
      a: "ら",
      s: "せ",
      d: "わ",
      f: "ろ",
      g: "そ",
      h: "ぎ",
      j: "ー",
      k: "め",
      l: "り",
      Semicolon: "を",
      z: "び",
      x: "ぇ",
      c: "げ",
      v: "ふ",
      b: "ざ",
      n: "ぐ",
      m: "む",
      Comma: "ゔ",
      Period: "ぅ",
      Slash: "ぢ",
    },
  },
];

const buna: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "こ",
      w: "に",
      e: "は",
      r: "て",
      t: "も",
      y: "り",
      u: "っ",
      i: "し",
      o: "の",
      p: "き",
      BracketLeft: "れ",
      a: "で",
      s: "か",
      d: "☆",
      f: "な",
      g: "た",
      h: "く",
      j: "ん",
      k: "★",
      l: "い",
      Semicolon: "と",
      Quote: "ら",
      z: "だ",
      x: "が",
      c: "ま",
      v: "す",
      b: "ょ",
      n: "る",
      m: "う",
      Comma: "、",
      Period: "。",
    },
  },
  {
    name: "☆シフト",
    diagram: {
      q: "づ",
      w: "＿",
      e: "ぢ",
      r: "ぷ",
      t: "ぅ",
      y: "ぬ",
      u: "ぱ",
      i: "げ",
      o: "じ",
      p: "ゃ",
      BracketLeft: "「",
      a: "ば",
      s: "さ",
      d: "☆",
      f: "ゅ",
      g: "ぜ",
      h: "ひ",
      j: "を",
      k: "め",
      l: "ー",
      Semicolon: "ぶ",
      Quote: "」",
      z: "ぴ",
      x: "ぞ",
      c: "＿",
      v: "ゆ",
      b: "ヴ",
      n: "ず",
      m: "む",
      Comma: "ぎ",
      Period: "ぐ",
      Slash: "ぽ",
      IntlRo: "",
    },
  },
  {
    name: "★シフト",
    diagram: {
      q: "べ",
      w: "ぼ",
      e: "ほ",
      r: "そ",
      t: "へ",
      y: "＿",
      u: "ぺ",
      i: "ぇ",
      o: "え",
      p: "や",
      BracketLeft: "",
      a: "わ",
      s: "せ",
      d: "け",
      f: "ど",
      g: "あ",
      h: "び",
      j: "つ",
      k: "★",
      l: "お",
      Semicolon: "ろ",
      Quote: "",
      z: "ふ",
      x: "ざ",
      c: "ご",
      v: "ね",
      b: "よ",
      n: "み",
      m: "ち",
      Comma: "ぉ",
      Period: "ぃ",
      Slash: "ぁ",
      IntlRo: "",
    },
  },
];

const hideduki: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "そ",
      w: "き",
      e: "し",
      r: "て",
      t: "は",
      y: "を",
      u: "ん",
      i: "い",
      o: "る",
      p: "ー",
      a: "す",
      s: "か",
      d: "★",
      f: "と",
      g: "た",
      h: "く",
      j: "う",
      k: "☆",
      l: "△",
      Semicolon: "；",
      z: "ち",
      x: "こ",
      c: "に",
      v: "な",
      b: "さ",
      n: "の",
      m: "り",
      Comma: "、",
      Period: "。",
      Slash: "・",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "ゐ",
      w: "お",
      e: "み",
      r: "え",
      t: "め",
      y: "へ",
      u: "ふ",
      i: "せ",
      o: "ゆ",
      p: "ぬ",
      a: "ね",
      s: "れ",
      d: "ら",
      f: "あ",
      g: "わ",
      h: "や",
      j: "ま",
      k: "も",
      l: "よ",
      Semicolon: "；",
      z: "ゑ",
      x: "ろ",
      c: "け",
      v: "ほ",
      b: "む",
      n: "ひ",
      m: "つ",
      Comma: "",
      Period: "",
      Slash: "・",
    },
  },
];

const burichutoro: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "ゅ",
      w: "こ",
      e: "と",
      r: "さ",
      t: "ゃ",
      y: "わ",
      u: "き",
      i: "し",
      o: "く",
      p: "ち",
      BracketLeft: "",
      a: "た",
      s: "か",
      d: "、",
      f: "て",
      g: "は",
      h: "の",
      j: "い",
      k: "。",
      l: "う",
      Semicolon: "ん",
      Quote: "ー",
      z: "ょ",
      x: "に",
      c: "な",
      v: "る",
      b: "も",
      n: "つ",
      m: "す",
      Comma: "お",
      Period: "あ",
      Slash: "っ",
    },
  },
  {
    name: "Kシフト",
    diagram: {
      q: "ひ",
      w: "ね",
      e: "ど",
      r: "め",
      t: "ふ",
      y: "ゔ",
      u: "ぎ",
      i: "ぃ",
      o: "ぐ",
      p: "ぢ",
      BracketLeft: "",
      a: "だ",
      s: "が",
      d: "を",
      f: "で",
      g: "ま",
      h: "ぁ",
      j: "り",
      k: "？",
      l: "れ",
      Semicolon: "",
      Quote: "/",
      z: "へ",
      x: "そ",
      c: "せ",
      v: "け",
      b: "ほ",
      n: "づ",
      m: "ず",
      Comma: "ぅ",
      Period: "ぇ",
      Slash: "ぉ",
      IntlRo: "",
    },
  },
  {
    name: "Dシフト",
    diagram: {
      q: "ぴ",
      w: "ご",
      e: "ぬ",
      r: "ざ",
      t: "ぷ",
      y: "む",
      u: "ゆ",
      i: "じ",
      o: "や",
      p: "ふぁ",
      BracketLeft: "",
      a: "ょう",
      s: "ら",
      d: "！",
      f: "よ",
      g: "ぱ",
      h: "ば",
      j: "ろ",
      k: "を",
      l: "ます",
      Semicolon: "ゅう",
      Quote: "~",
      z: "ぺ",
      x: "ぞ",
      c: "ぜ",
      v: "げ",
      b: "ぽ",
      n: "ぼ",
      m: "です",
      Comma: "え",
      Period: "み",
      Slash: "ふぉ",
      IntlRo: "",
    },
  },
];

const tsukimisou: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "だ",
      w: "か",
      e: "ゃ",
      r: "が",
      t: "を",
      u: "き",
      i: "ん",
      o: "た",
      p: "つ",
      BracketLeft: "ち",
      a: "に",
      s: "ょ",
      d: "う",
      f: "ゅ",
      g: "て",
      h: "こ",
      j: "っ",
      k: "い",
      l: "と",
      Semicolon: "く",
      Quote: "り",
      z: "で",
      x: "も",
      c: "ま",
      v: "の",
      b: "は",
      n: "し",
      m: "な",
      Comma: "る",
      Period: "す",
      Slash: "れ",
    },
  },
];

const fumiduki: LayoutDiagrams = [
  {
    name: "単打",
    diagram: {
      q: "も",
      w: "か",
      e: "し",
      r: "て",
      t: "よ",
      y: "つ",
      u: "ん",
      i: "い",
      o: "の",
      p: "ま",
      BracketLeft: "を",
      a: "は",
      s: "濁",
      d: "★",
      f: "た",
      g: "と",
      h: "く",
      j: "う",
      k: "☆",
      l: "濁",
      Semicolon: "が",
      Quote: "に",
      z: "よ",
      x: "せ",
      c: "す",
      v: "な",
      b: "で",
      n: "っ",
      m: "る",
      Comma: "、",
      Period: "。",
      Slash: "ー",
    },
  },
  {
    name: "シフト",
    diagram: {
      q: "　",
      w: "け",
      e: "れ",
      r: "そ",
      t: "ろ",
      y: "　",
      u: "み",
      i: "ふ",
      o: "や",
      p: "へ",
      BracketLeft: "　",
      a: "め",
      s: "さ",
      d: "き",
      f: "あ",
      g: "お",
      h: "り",
      j: "ら",
      k: "こ",
      l: "ゆ",
      Semicolon: "え",
      Quote: "　",
      z: "　",
      x: "ぬ",
      c: "ね",
      v: "ほ",
      b: "　",
      n: "む",
      m: "ち",
      Comma: "ひ",
      Period: "わ",
      Slash: "　",
      IntlRo: "　",
    },
  },
];

export const layoutDiagrams: Record<LayoutId, LayoutDiagrams> = {
  qwerty,
  oonisi,
  hana,
  "tsuki-2-263": tsuki2263,
  yukika,
  mizunara,
  "hybrid-tsuki": hybridTsuki,
  buna,
  hideduki,
  "burichutoro-20221015": burichutoro,
  tsukimisou,
  tukiringo,
  fumiduki,
};
